name: cost_averaging_trading_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  crypto: ^3.0.3
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  path: ^1.9.0
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  device_preview: ^1.1.0
  intl: ^0.19.0
  responsive_builder: ^0.7.0
  candlesticks: ^2.1.0
  web_socket_channel: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - .env
